const { loadCards, loadSettings, loadUsers, saveUsers, getActiveSession, setActiveSession, clearActiveSession } = window.TabuData;
const state={setupTeams:["Kadavra Ekibi"],teams:[],scores:[],activeTeamIndex:0,currentRound:1,timerId:null,remainingSeconds:60,cards:loadCards(),settings:loadSettings(),deck:[],history:[],currentTurn:{correct:0,taboo:0,pass:0}};
const e={setupScreen:qs('#setup-screen'),gameScreen:qs('#game-screen'),teamList:qs('#team-list'),addTeam:qs('#add-team-button'),startGame:qs('#start-game-button'),settingsSummary:qs('#settings-summary'),scoreboard:qs('#scoreboard'),resetGame:qs('#reset-game-button'),startTurn:qs('#start-turn-button'),finishTurn:qs('#finish-turn-button'),activeTeam:qs('#active-team'),roundLabel:qs('#round-label'),timer:qs('#timer'),targetWord:qs('#target-word'),forbiddenList:qs('#forbidden-list'),correct:qs('#correct-button'),taboo:qs('#taboo-button'),pass:qs('#pass-button'),passLimit:qs('#pass-limit'),turnCorrect:qs('#turn-correct'),turnTaboo:qs('#turn-taboo'),turnPass:qs('#turn-pass'),turnScore:qs('#turn-score'),roundHistory:qs('#round-history'),openAuth:qs('#open-auth-button'),authDialog:qs('#auth-dialog'),authForm:qs('#auth-form'),authUser:qs('#auth-username'),authMail:qs('#auth-mail'),authPass:qs('#auth-password'),authMsg:qs('#auth-message'),userPanel:qs('#user-panel')};
function qs(s){return document.querySelector(s)}
function fmt(ms){const d=Math.ceil(ms/86400000),h=Math.ceil(ms/3600000),m=Math.ceil(ms/60000);if(d>=1)return `${d} gün`;if(h>=1)return `${h} saat`;return `${m} dakika`;}
function renderUser(){const users=loadUsers();const s=getActiveSession();if(!s){e.openAuth.textContent='Giriş yap';e.userPanel.hidden=true;return;}const u=users.find(x=>x.username===s.username);if(!u)return clearActiveSession();if(u.bannedUntil&&Date.now()<u.bannedUntil){const rem=u.bannedUntil-Date.now();e.userPanel.hidden=false;e.userPanel.innerHTML=`<h2>Geçici yasaklandınız</h2><p>${fmt(rem)} kaldı. Geçici yasaklandınız, e-posta: ${u.email||'-'}</p>`;e.openAuth.textContent='Giriş yap';clearActiveSession();return;}if(u.role==='admin'){location.href='admin/';return;}e.openAuth.textContent=u.username;e.userPanel.hidden=false;e.userPanel.innerHTML=`<h2>Hesabım</h2><p>Kelimeler: ${state.cards.length} aktif</p><p>Hesap ayrıntılarım: ${u.email||'-'}</p>`;}
function auth(mode){const users=loadUsers();const username=e.authUser.value.trim();const password=e.authPass.value;const email=e.authMail.value.trim();if(mode==='register'){if(users.some(u=>u.username===username)){e.authMsg.textContent='Bu kullanıcı adı dolu';return;}users.push({username,password,email,role:'user',createdAt:new Date().toISOString()});saveUsers(users);e.authMsg.textContent='Kayıt başarılı';return;}const user=users.find(u=>u.username===username&&u.password===password);if(!user){e.authMsg.textContent='Bilgiler hatalı';return;}if(user.bannedUntil&&Date.now()<user.bannedUntil){e.authMsg.textContent=`Geçici yasak: ${fmt(user.bannedUntil-Date.now())}`;return;}setActiveSession({username:user.username});e.authDialog.close();renderUser();}
// game funcs condensed
function shuffle(a){return [...a].sort(()=>Math.random()-0.5)};function score(){return state.currentTurn.correct*state.settings.correctPoints-state.currentTurn.taboo*state.settings.tabooPenalty}
function renderSetupTeams(){e.teamList.replaceChildren(...state.setupTeams.map((t,i)=>{const r=document.createElement('div');r.className='team-row';r.innerHTML=`<label>${i+1}. takım</label><input maxlength='24' value='${t}'><button class='icon-button' type='button'>×</button>`;const inp=r.querySelector('input');inp.oninput=()=>state.setupTeams[i]=inp.value;r.querySelector('button').onclick=()=>{if(state.setupTeams.length>1){state.setupTeams.splice(i,1);renderSetupTeams();}};return r;}));}
function render(){e.settingsSummary.textContent=`${state.settings.roundSeconds} sn`;e.turnCorrect.textContent=state.currentTurn.correct;e.turnTaboo.textContent=state.currentTurn.taboo;e.turnPass.textContent=state.currentTurn.pass;e.turnScore.textContent=score();e.passLimit.textContent=state.settings.passLimit;e.scoreboard.replaceChildren(...state.teams.map((t,i)=>{const c=document.createElement('article');c.className='score-card'+(i===state.activeTeamIndex?' active':'');c.innerHTML=`<span>${t}</span><strong>${state.scores[i]}</strong>`;return c;}));e.activeTeam.textContent=state.teams[state.activeTeamIndex]||'Takım';e.roundLabel.textContent=`${state.currentRound}. Tur`;}
function card(){if(!state.deck.length)state.deck=shuffle(state.cards);const c=state.deck.pop();if(!c)return;e.targetWord.textContent=c.word;e.forbiddenList.replaceChildren(...c.forbidden.map(w=>{const li=document.createElement('li');li.textContent=w;return li;}));}
function prepare(){clearInterval(state.timerId);state.timerId=null;state.remainingSeconds=state.settings.roundSeconds;state.currentTurn={correct:0,taboo:0,pass:0};e.timer.textContent=state.remainingSeconds;render();}
function finish(){if(!state.timerId)return;clearInterval(state.timerId);state.timerId=null;const s=score();state.scores[state.activeTeamIndex]+=s;state.history.push({round:state.currentRound,team:state.teams[state.activeTeamIndex],score:s,...state.currentTurn});state.activeTeamIndex=(state.activeTeamIndex+1)%state.teams.length;if(state.activeTeamIndex===0)state.currentRound++;prepare();}
function start(){state.cards=loadCards();state.settings=loadSettings();state.teams=state.setupTeams.map((t,i)=>t.trim()||`${i+1}. Takım`);state.scores=state.teams.map(()=>0);e.setupScreen.hidden=true;e.gameScreen.hidden=false;prepare();}
[e.correct,e.taboo,e.pass].forEach((b,idx)=>b.onclick=()=>{if(!state.timerId)return;if(idx===0)state.currentTurn.correct++;if(idx===1)state.currentTurn.taboo++;if(idx===2&&state.currentTurn.pass<state.settings.passLimit)state.currentTurn.pass++;card();render();});
e.finishTurn.onclick=finish;e.startTurn.onclick=()=>{if(state.timerId)return;prepare();card();state.timerId=setInterval(()=>{state.remainingSeconds--;e.timer.textContent=state.remainingSeconds;if(state.remainingSeconds<=0)finish();},1000)};
e.startGame.onclick=start;e.addTeam.onclick=()=>{state.setupTeams.push(`${state.setupTeams.length+1}. Takım`);renderSetupTeams();};e.resetGame.onclick=()=>location.reload();
e.openAuth.onclick=()=>e.authDialog.showModal();qs('#login-button').onclick=(ev)=>{ev.preventDefault();auth('login')};qs('#register-button').onclick=(ev)=>{ev.preventDefault();auth('register')};
renderSetupTeams();render();renderUser();
